# Site settings
title: "Uğur Cibaroğlu"
email: ugur.cibar@gmail.com
description: "Uğur Cibaroğlu'nun kişisel blogu. Karabük üniversitesi Bilgisayar mühendisliği öğrencisi."
baseurl: ""
url: "http://ugurcibar.com"
title_description: "Bilgisayar mühendisliği öğrencisi, acemi yazılım ve oyun geliştirici, Kendi çapında oyun eleştirmeni."
title_image: ""
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: uCibar
github_username:  uCibar

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
