title: Uğur Cibaroğlu
description: Uğur Cibaroğlu, bilgisayar mühendisliği öğrencisi, yazılım ve oyun geliştirici.
author: Uğur Cibaroğlu
github: https://github.com/uCibar
about: Computer Engineering Student

baseurl: ""
url: "http://ugurcibar.com"

disqus_shortname: ugurcibar
google_analytics: UA-89167633-1

share:
  twitter_username: \uCibar


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
