# Site settings
title: "Uğur Cibaroğlu"
email: ugur.cibar@gmail.com
description: "Uğur Cibaroğlu'nun kişisel blogu. Karabük üniversitesi Bilgisayar mühendisliği öğrencisi."
baseurl: ""
url: "http://ugurcibar.com"
title_description: "Bilgisayar mühendisliği öğrencisi, acemi yazılım ve oyun geliştirici, Kendi çapında oyun eleştirmeni."
title_image: ""
google_analytics: ""
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: uCibar
github_username:  uCibar
steam_username:  redostr

# Footer
footer_left: "Powered by <a href=\"https://github.com/jekyll/jekyll\">Jekyll</a> and <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte-Noire</a> theme."
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
