# Site settings
title: "Uğur Cibaroğlu"
email: ugur.cibar@gmail.com
description: "Uğur Cibaroğlu'nun kişisel blogu. Karabük üniversitesi Bilgisayar mühendisliği öğrencisi."
baseurl: ""
url: "http://ugurcibar.com"
title_description: "Merhaba, Ben Uğur.<br><br>
Karabük üniversitesinde Bilgisayar mühendisliği öğrencisiyim.
Yazılım dünyasına web teknolojileri ile giriş yaptım. PHP, Ruby, CodeIgniter, Rails, NodeJS gibi dostlarım oldu.<br><br>
Web'den ve CRUD app'lerden sıkılınca, oyun geliştirmeye merak saldım. Elimden geldiğince oyun ve yazılım geliştirme maceralarımı buradan paylaşacağım."
title_image: ""
google_analytics: ""
disqus_account: ugurcibar
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-584c2204974683fc
post_limit: 5

# Social usernames/URLs
twitter_username: uCibar
github_username:  uCibar
steam_username:  redostr

# Footer
footer_left: "Powered by <a href=\"https://github.com/jekyll/jekyll\">Jekyll</a> and <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte-Noire</a> theme."
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
